# Generated by Django 4.0.4 on 2022-05-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormulario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Registro',
        ),
    ]
